module.exports = {
  'import/no-unresolved': 'off',
  'react-hooks/rules-of-hooks': 'error',
  'react-hooks/exhaustive-deps': 'off',
  'react/jsx-pascal-case': ['warn', { allowAllCaps: true, ignore: [] }],
  '@typescript-eslint/no-explicit-any': 'off',
  'react/prop-types': 'off',
  'react/react-in-jsx-scope': 'off',
  camelcase: 'error',
  'spaced-comment': 'error',
  quotes: ['error', 'single'],
  'no-duplicate-imports': 'error',
  'max-len': [
    'error',
    {
      code: 250,
    },
  ],
  'no-console': 'error',
  'react/self-closing-comp': ['error', { component: true, html: true }],
  '@typescript-eslint/no-extraneous-class': 'off',
  semi: 'off',
  '@typescript-eslint/semi': ['error', 'always'],
  'import/default': 'off',
  'import/no-useless-path-segments': 'error',
  'import/no-duplicates': 'error',
  'import/no-empty-named-blocks': 'error',
  '@typescript-eslint/import/prefer-default-export': 'off',
  '@typescript-eslint/no-unused-expressions': [
    'error',
    { allowShortCircuit: true, allowTernary: true, allowTaggedTemplates: true },
  ],
  'react/jsx-filename-extension': [
    2,
    {
      extensions: ['.js', 'ts', '.jsx', '.tsx'],
    },
  ],
  'import/order': [
    'error',
    {
      groups: ['builtin', 'external', 'internal', ['parent', 'sibling']],
      pathGroups: [
        {
          pattern: 'react',
          group: 'external',
          position: 'before',
        },
      ],
      pathGroupsExcludedImportTypes: ['react'],
      alphabetize: {
        order: 'asc',
        caseInsensitive: true,
      },
    },
  ],
  '@typescript-eslint/prefer-nullish-coalescing': 0,
  '@typescript-eslint/strict-boolean-expressions': 0,
  '@typescript-eslint/no-useless-constructor': 0,
  'constructor-super': 'error',
  'for-direction': 'error',
  'getter-return': 'error',
  'no-async-promise-executor': 'error',
  'no-case-declarations': 'error',
  'no-class-assign': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': 'error',
  'no-const-assign': 'error',
  'no-constant-condition': 'error',
  'no-delete-var': 'error',
  'no-dupe-args': 'error',
  'no-dupe-class-members': 'error',
  'no-dupe-else-if': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-empty': 'error',
  'no-empty-pattern': 'error',
  'no-ex-assign': 'error',
  'no-extra-boolean-cast': 'error',
  'no-fallthrough': 'error',
  'no-func-assign': 'error',
  'no-global-assign': 'error',
  'no-import-assign': 'error',
  'no-inner-declarations': 'error',
  'no-irregular-whitespace': 'error',
  'no-loss-of-precision': 'error',
  'no-misleading-character-class': 'error',
  'no-mixed-spaces-and-tabs': 'error',
  'no-new-symbol': 'error',
  'no-nonoctal-decimal-escape': 'error',
  'no-obj-calls': 'error',
  'no-octal': 'error',
  'no-prototype-builtins': 'error',
  'no-redeclare': 'error',
  'no-self-assign': 'error',
  'no-setter-return': 'error',
  'no-shadow-restricted-names': 'error',
  'no-sparse-arrays': 'error',
  'no-this-before-super': 'error',
  'no-unexpected-multiline': 'error',
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'no-unsafe-optional-chaining': 'error',
  'no-unused-labels': 'error',
  'no-useless-backreference': 'error',
  'no-useless-catch': 'error',
  'no-useless-escape': 'error',
  'no-with': 'error',
  'require-yield': 'error',
  'use-isnan': 'error',
  'valid-typeof': 'error',
  'react/no-children-prop': 'off',
};
